language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --ignore=E402,E731,F401,F811 --exclude=migrations,south_migrations dbmail
script:
  - make test
  - make coverage
env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.13
  - DJANGO=1.9.9
  - DJANGO=1.10.1
branches:
  only:
    - master
    - development
