language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev redis-server
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --ignore=E402 --exclude=migrations,south_migrations dbmail
script:
  - make test
  - make coverage
env:
  - DJANGO=1.4.19
  - DJANGO=1.5.12
  - DJANGO=1.6.10
  - DJANGO=1.7.6
  - DJANGO=1.8c1
branches:
  only:
    - master
    - development
